# Generated by Django 5.2.1 on 2025-06-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0002_chaivarity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
